### ISSUE TITLE
Error when running plate-tectonics-and-earthquakes.ipynb notebook

### ISSUE THREAD

**Issue by nkinar** [EarthByte/miscellaneous-notebooks#3]
Hello,

I am attempting to run the plate-tectonics-and-earthquakes.ipynb notebook, and I find that for this following code, an error occurs:

```
# Set up the figure
fig = plt.figure(figsize=(14,7))
#fig.add_axes([0,0,0.9,1.0])

# Projections are rectangular, mollweide or robinson
ax = tutorial.create_map('robinson')

# You can plot different layers of information. Just remove the # before the layer name.
layers = [
    'coastlines',
    'topologies',
    'fracture',
    'velocities'
]

tutorial.plot_layers(layers, ax)
plt.show()
```

The error is the following:

![image](https://github.com/EarthByte/miscellaneous-notebooks/assets/407809/d009cfb7-de33-42fa-b4b4-8d53a21ff269)

Is this something with the shapely library?  How can I fix this?

Thanks.

**Comment by nkinar** [comment]
Apparently there have been some changes to the shapely library.  I had to fix the following function and also ensure that the LineString and MultiLineString objects are imported.  Then the script was able to run without issues.  Note how the code checks for a difference between the LineString and MultiLineString.   This change is made in the `tut.py` file.

   ```
 def plot_fracture_zones(self, ax, color='default'):
        #plot the fracture zones
        print('Plotting fracture zones...')
        
        for record in Reader(fracture_zones_output_basename).records():

            c=color
            if color == 'default':
                c = plate_tectonic_utils.get_colour_by_plateid(int(record.attributes['PLATEID1']))
            
            elem = record.geometry 
            if isinstance(elem, LineString):
                lon, lat = elem.xy
                ax.plot(lon,lat,transform=ccrs.Geodetic(),color=c)
            elif isinstance(elem, MultiLineString):
                for line in elem.geoms:
                    lon, lat = line.xy
                    ax.plot(lon,lat,transform=ccrs.Geodetic(),color=c)
                else:
                    pass
```

**Comment by michaelchin** [comment]
Thanks @nkinar

I have updated the code in b3c4073

**Comment by nkinar** [comment]
Thanks for the update; that is great to know!
